apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-pipeline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/uz0/core-charts.git  # Update with your repo URL
    targetRevision: main
    path: core-pipeline  # Update with the path to your core-pipeline chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Update with your target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m