#!/usr/bin/expect -f

set timeout 120
spawn ssh -i ~/.ssh/uz0 root@46.62.223.198

expect "password:"
send "123454\r"

# Delete existing ArgoCD applications
expect "# "
send "kubectl delete application core-pipeline-dev core-pipeline-prod -n argocd --ignore-not-found\r"

# Create dev namespace and resources
expect "# "
send "cat <<'EOF' | kubectl apply -f -\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Namespace\r"
send "metadata:\r"
send "  name: dev-core\r"
send "---\r"
send "apiVersion: apps/v1\r"
send "kind: Deployment\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: dev-core\r"
send "  labels:\r"
send "    app: core-pipeline\r"
send "spec:\r"
send "  replicas: 1\r"
send "  selector:\r"
send "    matchLabels:\r"
send "      app: core-pipeline\r"
send "  template:\r"
send "    metadata:\r"
send "      labels:\r"
send "        app: core-pipeline\r"
send "    spec:\r"
send "      containers:\r"
send "      - name: core-pipeline\r"
send "        image: nginx:latest\r"
send "        ports:\r"
send "        - containerPort: 80\r"
send "          name: http\r"
send "        env:\r"
send "        - name: ENV\r"
send "          value: development\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Service\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: dev-core\r"
send "spec:\r"
send "  selector:\r"
send "    app: core-pipeline\r"
send "  ports:\r"
send "  - port: 80\r"
send "    targetPort: 80\r"
send "    name: http\r"
send "---\r"
send "apiVersion: networking.k8s.io/v1\r"
send "kind: Ingress\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: dev-core\r"
send "  annotations:\r"
send "    nginx.ingress.kubernetes.io/backend-protocol: HTTP\r"
send "spec:\r"
send "  ingressClassName: nginx\r"
send "  rules:\r"
send "  - host: core-pipeline.dev.theedgestory.org\r"
send "    http:\r"
send "      paths:\r"
send "      - path: /\r"
send "        pathType: Prefix\r"
send "        backend:\r"
send "          service:\r"
send "            name: core-pipeline\r"
send "            port:\r"
send "              number: 80\r"
send "EOF\r"

# Create prod namespace and resources
expect "# "
send "cat <<'EOF' | kubectl apply -f -\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Namespace\r"
send "metadata:\r"
send "  name: prod-core\r"
send "---\r"
send "apiVersion: apps/v1\r"
send "kind: Deployment\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: prod-core\r"
send "  labels:\r"
send "    app: core-pipeline\r"
send "spec:\r"
send "  replicas: 2\r"
send "  selector:\r"
send "    matchLabels:\r"
send "      app: core-pipeline\r"
send "  template:\r"
send "    metadata:\r"
send "      labels:\r"
send "        app: core-pipeline\r"
send "    spec:\r"
send "      containers:\r"
send "      - name: core-pipeline\r"
send "        image: nginx:latest\r"
send "        ports:\r"
send "        - containerPort: 80\r"
send "          name: http\r"
send "        env:\r"
send "        - name: ENV\r"
send "          value: production\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Service\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: prod-core\r"
send "spec:\r"
send "  selector:\r"
send "    app: core-pipeline\r"
send "  ports:\r"
send "  - port: 80\r"
send "    targetPort: 80\r"
send "    name: http\r"
send "---\r"
send "apiVersion: networking.k8s.io/v1\r"
send "kind: Ingress\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: prod-core\r"
send "  annotations:\r"
send "    nginx.ingress.kubernetes.io/backend-protocol: HTTP\r"
send "spec:\r"
send "  ingressClassName: nginx\r"
send "  rules:\r"
send "  - host: core-pipeline.prod.theedgestory.org\r"
send "    http:\r"
send "      paths:\r"
send "      - path: /\r"
send "        pathType: Prefix\r"
send "        backend:\r"
send "          service:\r"
send "            name: core-pipeline\r"
send "            port:\r"
send "              number: 80\r"
send "EOF\r"

# Check deployments
expect "# "
send "kubectl get all -n dev-core\r"

expect "# "
send "kubectl get all -n prod-core\r"

expect "# "
send "exit\r"
expect eof