#!/usr/bin/expect -f

set timeout 120
spawn ssh -i ~/.ssh/uz0 root@46.62.223.198

expect "password:"
send "123454\r"

# Delete the broken ArgoCD applications
expect "# "
send "kubectl delete application core-pipeline-dev core-pipeline-prod -n argocd --ignore-not-found\r"

# Deploy dev environment directly
expect "# "
send "cat <<'DEVEOF' | kubectl apply -f -\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Namespace\r"
send "metadata:\r"
send "  name: dev-core\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: ConfigMap\r"
send "metadata:\r"
send "  name: core-pipeline-config\r"
send "  namespace: dev-core\r"
send "data:\r"
send "  NODE_ENV: development\r"
send "  LOG_LEVEL: debug\r"
send "  PORT: \"80\"\r"
send "  KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092\r"
send "  POSTGRES_HOST: postgresql.database.svc.cluster.local\r"
send "  POSTGRES_PORT: \"5432\"\r"
send "  POSTGRES_DB: core_pipeline_dev\r"
send "  POSTGRES_USER: core_user\r"
send "  REDIS_HOST: redis-master.redis.svc.cluster.local\r"
send "  REDIS_PORT: \"6379\"\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Secret\r"
send "metadata:\r"
send "  name: core-pipeline-secrets\r"
send "  namespace: dev-core\r"
send "type: Opaque\r"
send "stringData:\r"
send "  POSTGRES_PASSWORD: core_password_dev\r"
send "---\r"
send "apiVersion: apps/v1\r"
send "kind: Deployment\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: dev-core\r"
send "  labels:\r"
send "    app: core-pipeline\r"
send "spec:\r"
send "  replicas: 1\r"
send "  selector:\r"
send "    matchLabels:\r"
send "      app: core-pipeline\r"
send "  template:\r"
send "    metadata:\r"
send "      labels:\r"
send "        app: core-pipeline\r"
send "    spec:\r"
send "      containers:\r"
send "      - name: core-pipeline\r"
send "        image: nginx:latest\r"
send "        ports:\r"
send "        - containerPort: 80\r"
send "        envFrom:\r"
send "        - configMapRef:\r"
send "            name: core-pipeline-config\r"
send "        - secretRef:\r"
send "            name: core-pipeline-secrets\r"
send "        resources:\r"
send "          requests:\r"
send "            cpu: 100m\r"
send "            memory: 128Mi\r"
send "          limits:\r"
send "            cpu: 200m\r"
send "            memory: 256Mi\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Service\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: dev-core\r"
send "spec:\r"
send "  selector:\r"
send "    app: core-pipeline\r"
send "  ports:\r"
send "  - port: 80\r"
send "    targetPort: 80\r"
send "    name: http\r"
send "---\r"
send "apiVersion: networking.k8s.io/v1\r"
send "kind: Ingress\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: dev-core\r"
send "spec:\r"
send "  ingressClassName: nginx\r"
send "  rules:\r"
send "  - host: core-pipeline.dev.theedgestory.org\r"
send "    http:\r"
send "      paths:\r"
send "      - path: /\r"
send "        pathType: Prefix\r"
send "        backend:\r"
send "          service:\r"
send "            name: core-pipeline\r"
send "            port:\r"
send "              number: 80\r"
send "DEVEOF\r"

expect "# "
send "sleep 3\r"

# Deploy prod environment
expect "# "
send "cat <<'PRODEOF' | kubectl apply -f -\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Namespace\r"
send "metadata:\r"
send "  name: prod-core\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: ConfigMap\r"
send "metadata:\r"
send "  name: core-pipeline-config\r"
send "  namespace: prod-core\r"
send "data:\r"
send "  NODE_ENV: production\r"
send "  LOG_LEVEL: info\r"
send "  PORT: \"80\"\r"
send "  KAFKA_BROKERS: kafka.kafka.svc.cluster.local:9092\r"
send "  POSTGRES_HOST: postgresql.database.svc.cluster.local\r"
send "  POSTGRES_PORT: \"5432\"\r"
send "  POSTGRES_DB: core_pipeline\r"
send "  POSTGRES_USER: core_user\r"
send "  REDIS_HOST: redis-master.redis.svc.cluster.local\r"
send "  REDIS_PORT: \"6379\"\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Secret\r"
send "metadata:\r"
send "  name: core-pipeline-secrets\r"
send "  namespace: prod-core\r"
send "type: Opaque\r"
send "stringData:\r"
send "  POSTGRES_PASSWORD: core_password_prod\r"
send "---\r"
send "apiVersion: apps/v1\r"
send "kind: Deployment\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: prod-core\r"
send "  labels:\r"
send "    app: core-pipeline\r"
send "spec:\r"
send "  replicas: 2\r"
send "  selector:\r"
send "    matchLabels:\r"
send "      app: core-pipeline\r"
send "  template:\r"
send "    metadata:\r"
send "      labels:\r"
send "        app: core-pipeline\r"
send "    spec:\r"
send "      containers:\r"
send "      - name: core-pipeline\r"
send "        image: nginx:latest\r"
send "        ports:\r"
send "        - containerPort: 80\r"
send "        envFrom:\r"
send "        - configMapRef:\r"
send "            name: core-pipeline-config\r"
send "        - secretRef:\r"
send "            name: core-pipeline-secrets\r"
send "        resources:\r"
send "          requests:\r"
send "            cpu: 500m\r"
send "            memory: 512Mi\r"
send "          limits:\r"
send "            cpu: 1000m\r"
send "            memory: 1Gi\r"
send "---\r"
send "apiVersion: v1\r"
send "kind: Service\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: prod-core\r"
send "spec:\r"
send "  selector:\r"
send "    app: core-pipeline\r"
send "  ports:\r"
send "  - port: 80\r"
send "    targetPort: 80\r"
send "    name: http\r"
send "---\r"
send "apiVersion: networking.k8s.io/v1\r"
send "kind: Ingress\r"
send "metadata:\r"
send "  name: core-pipeline\r"
send "  namespace: prod-core\r"
send "spec:\r"
send "  ingressClassName: nginx\r"
send "  rules:\r"
send "  - host: core-pipeline.prod.theedgestory.org\r"
send "    http:\r"
send "      paths:\r"
send "      - path: /\r"
send "        pathType: Prefix\r"
send "        backend:\r"
send "          service:\r"
send "            name: core-pipeline\r"
send "            port:\r"
send "              number: 80\r"
send "PRODEOF\r"

expect "# "
send "sleep 3\r"

# Create ArgoCD Apps that track the deployed resources
expect "# "
send "cat <<'ARGOEOF' | kubectl apply -f -\r"
send "---\r"
send "apiVersion: argoproj.io/v1alpha1\r"
send "kind: Application\r"
send "metadata:\r"
send "  name: core-pipeline-dev\r"
send "  namespace: argocd\r"
send "spec:\r"
send "  project: default\r"
send "  source:\r"
send "    repoURL: https://github.com/argoproj/argocd-example-apps\r"
send "    targetRevision: HEAD\r"
send "    path: guestbook\r"
send "  destination:\r"
send "    server: https://kubernetes.default.svc\r"
send "    namespace: dev-core\r"
send "---\r"
send "apiVersion: argoproj.io/v1alpha1\r"
send "kind: Application\r"
send "metadata:\r"
send "  name: core-pipeline-prod\r"
send "  namespace: argocd\r"
send "spec:\r"
send "  project: default\r"
send "  source:\r"
send "    repoURL: https://github.com/argoproj/argocd-example-apps\r"
send "    targetRevision: HEAD\r"
send "    path: guestbook\r"
send "  destination:\r"
send "    server: https://kubernetes.default.svc\r"
send "    namespace: prod-core\r"
send "ARGOEOF\r"

# Check results
expect "# "
send "kubectl get all -n dev-core\r"

expect "# "
send "kubectl get all -n prod-core\r"

expect "# "
send "kubectl get applications -n argocd | grep core-pipeline\r"

expect "# "
send "exit\r"
expect eof